name: Lint commit messages

on: [push, pull_request]

jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Validate commits with commitlint
        uses: wagoid/commitlint-github-action@v6
